spring:
  application:
    name:
      information-security
  datasource:
    url: jdbc:postgresql://localhost:5432/information_security
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  mail:
    host: smtp.mail.ru
    port: 587
    username: bayanovv8091@mail.ru
    password: Q7SPjJk33mfriDSauJUE
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp